spring:
  data:
    redis:
      port: 6379 # Redis 服务器端口
      host: 127.0.0.1 # Redis 服务器地址
      database: 0 # Redis 数据库索引，默认为0
      password:   # Redis 服务器密码，默认为空
      lettuce:
        pool:
          min-idle: 10 # Redis 连接池中的最大空闲数，默认为 0
          max-idle: 20 # Redis 连接池中的最大空闲书，默认为 8
          max-active: 100 # 连接池的最大连接数，默认为 8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: password

drivesaf:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c8cd4da0a018ef183614566d3
      accountToken: 2cc3ca264c0f4785a15edaebeba8aa9d
      appId: 2c94811c8cd4da0a018ef18362bb66da
      templateId: 1

# 配置 MP 框架⽇志级别
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
# MP 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰下划线转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试⽤
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        # 扫描 controller 包的路径，⾃⾏修改
        packages-to-scan: io.drivesaf.springboot.redis.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
    basic:
      enable: true
      username: admin
      password: 123456


