server:
  host: "localhost"
  port: 8080
  context-path: "/api"

person:
  first-name: ${first-name:Jhon}
  last-name: ${last-name:Doe}
  age: ${random.int(20,50)}
  id: ${random.uuid}
  phone: ${phone.number:1234567890}

family:
  family-name: "happy"
  father: "${father.name:zhangsan}"
  mother: "Rose2222"
  child: "Tom"
  age: "${random.int(5,30)}"

father:
  name: "Jack"

student:
  name: 张⼩⻜
  age: 20
  happy: true
  birth: 2004/01/01
  map: {k1: v1,k2: v2}
  list:
    - code
    - read
    - music
  dog:
    name: ⻁⼦
    age: 11

custom:
  qrcode:
    content: "https://www.bilibili.com"
  log:
    level: "INFO"
  backup:
    location: D:\backup.log

spring:
  web:
    resources:
      static-locations: classpath:/static/,file:${file.upload-path}
    servlet:
      multipart:
        max-file-size: 10485760 # 上传⽂件⼤⼩限定为10M
        max-request-size: 10485760
  mail:
    host: smtp.qq.com
    username: axao@foxmail.com
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

db:
  url: jdbc:mysql://localhost:3306/spring_boot?useSSL=false&serverTimezone=UTC
  username: root
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: mySecretKey # JWT密钥
  expiration: 3600000 # 1⼩时，单位为毫秒
